import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";

import FooterMenu from "../components/FooterMenu";

const inter = Inter({ subsets: ["latin"] });

const menuItems = [
  {
    name: "Settings",
    link: "/settings",
    description: "Learn how to Play the Game",
  },
  {
    name: "Riddles",
    link: "/help",
    description: "Play different varieties of riddles",
  },
  {
    name: "Fun Facts",
    link: "/fun-facts",
    description: "Play different varieties of riddles",
  },
  {
    name: "Trival Game",
    link: "/help",
    description: "Play different varieties of riddles",
  },
];

export const getStaticProps = async () => {
  try {
    const res = await fetch("http://localhost:5100/gen/questions");
    const data = (await res.json()) as string;
    return {
      props: {
        data,
      },
    };
  } catch (error) {
    return {
      props: {
        data:[]
      },
    };
  }
};

interface Props {
  data: any;
}

export default function Home({ data }: Props = { data: "test" }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>Test your knowledge!!</p>
          {JSON.stringify(data)}
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{" "}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          {/*    <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          /> */}
          <div className={styles.thirteen}>Start The Game</div>
        </div>

        <FooterMenu menuItems={menuItems} />

      </main>
    </>
  );
}
